# Generated by Django 4.1.5 on 2023-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zip',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
