# Generated by Django 4.1.5 on 2023-01-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_zip'),
    ]

    operations = [
        migrations.RunSQL('''
        INSERT INTO store_collection(title)
        VALUES ('collection1')
        ''','''
        DELETE FROM store_collection
        WHERE title='collection1'
        ''')
    ]
